### ISSUE TITLE
Return to a pure Sync API

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-kernel-rs#28]
**TDLR**: return the API to be synchronous. Make the Rust default TableClient use async in it's implementation, by embedding a reference to a runtime/executor.

## Why not async?

* Async API brings complexity to the FFI layer
* Async call stacks can be more difficult to debug
* Offering _both_ a sync and async API will be too much maintenance burden. In prototyping a parallel API, we found there was no way around writing duplicate code. See: #25

## How can TableClient default impl still use async?

Async is most valuable at the IO level to bring IO concurrency, so our TableClient methods should be designed to allow for concurrent IO operations in an async runtime.

For example, consider the `FileSystemClient`.

https://github.com/delta-incubator/delta-kernel-rs/blob/fb55e4081fb2c3ffe62310ee8868230f2d375bf2/kernel/src/lib.rs#L131-L138

The `list_from` method could be a synchronous iterator, but under the hood the implementation could use asynchronous calls to buffer the next page. Similarly, `read_files` could also be implemented with async calls to read files concurrently.

## Implementing correctly

If we want to run async functions inside of sync helpers, we need to submit them to some sort of executor. Thus, a table client that wants to run async tasks needs to hold a reference to an executor itself. 

The main danger to be avoided is calling `tokio::Runtime::block_on()` from within one of the helpers. Users might wrap the kernel high-level APIs in a tokio runtime, and tokio will panic if `block_on()` is called while inside an async runtime.

We may wish to make it so the user could configure the executor used. For example, they might want to pass down their own tokio runtime.

**Comment by mmgeorge** [comment]
I understand why this was done, but I think this change makes it quite difficult to integrate with web clients which cannot block. Not sure if anyone has any tips or has tried this yet? Without support for atomics / shared memory which require certain flags, I think I'm forced to either maintain a separate async fork or try do to something hacky like throwing specific retry errors and caching everything.
