### ISSUE TITLE
Inconsistency in the last checkpoint metadata field naming: snake_case used instead of camelCase

### ISSUE THREAD

**Issue by hackintoshrao** [delta-io/delta-kernel-rs#326]
While investigating snapshot creation for earlier versions (PR #322), I uncovered an inconsistency in how checkpoint metadata fields are named in the `_last_checkpoint` file.

**Current Behavior:**
The `_last_checkpoint` file contains fields in snake_case format. For example:
```json
{"size":8,"size_in_bytes":21857,"version":1}
```

**Expected Behavior:**
According to the [Delta Protocol specification](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#last-checkpoint-file-schema), these fields should be in camelCase. The expected format should be:
```json
{"size":8,"sizeInBytes":21857,"version":1}
```

**Impact:**
This inconsistency causes issues with deserialization when the `CheckpointMetadata` struct is annotated with `#[serde(rename_all = "camelCase")]`, leading to some fields (like `size_in_bytes`) being incorrectly set to `None`.

**Current Workaround:**
We've temporarily addressed this in PR #322 by adding an alias to the affected field:
```rust
#[serde(alias = "size_in_bytes")]
pub(crate) size_in_bytes: Option<i64>,
```

**Proposed Long-term Solution:**
1. Investigate why `delta-rs` is writing checkpoint metadata in snake_case instead of camelCase.
2. Update the checkpoint writing logic to use camelCase field names, aligning with the Delta protocol specification.
3. Update the `CheckpointMetadata` struct to expect camelCase without needing aliases.
4. If backwards compatibility is required, implement a more robust deserialization that can handle both camelCase and snake_case variants.

**Questions to Address:**
1. Was the use of snake_case a deliberate choice? If so, what was the reasoning?
2. Are there any backward compatibility concerns we need to consider when fixing this?
3. Are there any other parts of the codebase affected by this inconsistency?

**Comment by scovich** [comment]
> Investigate why delta-rs is writing checkpoint metadata in snake_case instead of camelCase.

My guess: rust clippy enforces snake_case for identifiers, and the automatic json serde will automatically follow that convention unless instructed to convert it.

**Comment by feniljain** [comment]
Corresponding PR on the `delta-rs` is merged :)

**Comment by zachschuermann** [comment]
Given this is fixed in delta-rs now, and the alias never landed in kernel, seems we can close this issue and only read the field as `camelCase`. Given `_last_checkpoint` files are rather ephemeral I wouldn't think we need to keep around the ability to read the incorrectly-written field?
